apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: davp-demo37-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: davp-demo37-3 
  name: davp-demo37-3
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: davp-demo37-3 
